<?php
/**
 * Lollum
 * 
 * Fonts array
 *
 * @package WordPress
 * @subpackage Lollum Themes
 * @author Lollum <support@lollum.com>
 *
 */

$web_fonts = array (
	'Arial, Helvetica, sans-serif',
	'Arial Black, Gadget, sans-serif',
	'Bookman Old Style, serif',
	'Courier New, Courier, monospace',
	'Garamond, serif',
	'Georgia, serif',
	'Helvetica Neue, Helvetica, Arial, sans-serif',
	'Impact, Charcoal, sans-serif',
	'Lucida Console, Monaco, monospace',
	'Lucida Sans Unicode, Lucida Grande, sans-serif',
	'MS Sans Serif, Geneva, sans-serif',
	'Tahoma, Geneva, sans-serif',
	'Times New Roman, Times, serif',
	'Verdana, Geneva, sans-serif'
);

$google_fonts = array (
	'Abel',
	'Actor',
	'Amaranth',
	'Arimo',
	'Arvo',
	'Asap',
	'Bitter',
	'Brawler',
	'Bree Serif',
	'Cabin Condensed',
	'Cabin',
	'Cantarell',
	'Cardo',
	'Changa One',
	'Chivo',
	'Coda',
	'Copse',
	'Crafty Girls',
	'Crete Round',
	'Crimson Text',
	'Cuprum',
	'Dancing Script',
	'Didact Gothic',
	'Doppio One',
	'Dosis',
	'Droid Sans',
	'Droid Serif',
	'Exo',
	'Francois One',
	'Gentium Book Basic',
	'Goudy Bookletter 1911',
	'Gudea',
	'Handlee',
	'IM Fell English',
	'Inconsolata',
	'Jockey One',
	'Josefin Sans',
	'Kameron',
	'Karla',
	'Kreon',
	'Lato',
	'Leckerli One',
	'Lobster Two',
	'Lobster',
	'Lora',
	'Maiden Orange',
	'Mako',
	'Maven Pro',
	'Merriweather',
	'Metamorphous',
	'Metrophobic',
	'Molengo',
	'Montserrat',
	'Mountains of Christmas',
	'Muli',
	'Neucha',
	'Neuton',
	'News Cycle',
	'Nobile',
	'Nunito',
	'Open Sans Condensed',
	'Open Sans',
	'Orienta',
	'Oswald',
	'Pacifico',
	'Patrick Hand',
	'Patua One',
	'Philosopher',
	'Play',
	'Playfair Display',
	'Pontano Sans',
	'PT Sans Narrow',
	'PT Sans',
	'PT Serif Caption',
	'PT Serif',
	'Puritan',
	'Questrial',
	'Quicksand',
	'Raleway',
	'Roboto',
	'Roboto Condensed',
	'Roboto Slab',
	'Rochester',
	'Rokkitt',
	'Ropa Sans',
	'Rosario',
	'Schoolbell',
	'Shadows Into Light',
	'Share',
	'Signika',
	'Source Sans Pro',
	'Spirax',
	'Sunshiney',
	'Tangerine',
	'Tinos',
	'Ubuntu Condensed',
	'Ubuntu',
	'Unkempt',
	'Varela Round',
	'Varela',
	'Vollkorn',
	'Yanone Kaffeesatz',
	'Yellowtail'
);