<?php
/**
 * Lollum
 * 
 * Backgrounds array
 *
 * @package WordPress
 * @subpackage Lollum Themes
 * @author Lollum <support@lollum.com>
 *
 */

$lol_images_bg = array(
	'3px Tile',
	'Absurdity',
	'Always Grey',
	'Arabesque',
	'Argyle',
	'Asfalt',
	'Assault',
	'Batthern',
	'Black Denim',
	'Black Mamba',
	'Black Thread',
	'Black Linen',
	'Blizzard',
	'Brillant',
	'Broken Noise',
	'Brushed Alum Dark',
	'Brushed Alum',
	'Burried',
	'Cartographer',
	'Chruch',
	'Classy Fabric',
	'Clean Grey Paper',
	'Clean Textile',
	'Climpek',
	'Corrugation',
	'Crisp Paper Ruffles',
	'Crissxcross',
	'Cross Scratches',
	'Crossed Stripes',
	'Cubes',
	'Cutcube',
	'Dark Brick Wall',
	'Dark Denim 3',
	'Dark Denim',
	'Dark Dotted',
	'Dark Geometric',
	'Dark Leather',
	'Dark Matter',
	'Dark Mosaic',
	'Dark Wood',
	'Diagonal Noise',
	'Diamond Upholstery',
	'Dirty Old Shirt',
	'Dust',
	'Escheresque',
	'Fabric Plaid',
	'Farmer',
	'Gplay',
	'Gradient Squares',
	'Grey Floral',
	'Ice Age',
	'Inflicted',
	'Knitted Netting',
	'Light Aluminium',
	'Light Honeycomb',
	'Light Mesh',
	'Light Paper Fibers',
	'Light Sketch',
	'Light Squares',
	'Light Wool',
	'Linen',
	'Little Triangles',
	'Low Contrast Linen',
	'Lyonnette',
	'Nami',
	'Noise Lines',
	'Padded',
	'Paper',
	'Pinstripe',
	'Pinstriped Suit',
	'Project Papper',
	'Psychedelic',
	'Purty Wood',
	'Pyramid',
	'Quilt',
	'Random Grey Variations',
	'Ravenna',
	'Retina Dust',
	'Retina Wood',
	'Retro Intro',
	'Rice Paper',
	'Scribble Light',
	'Shine Caro',
	'Shine Dotted',
	'Skewed Print',
	'Small Crackle Bright',
	'Snow',
	'Soft Pad',
	'Stacked Circles',
	'Stitched Wool',
	'Strange Bullseyes',
	'Subtle Dark Vertical',
	'Subtle Dots',
	'Subtle Stripes',
	'Subtle Surface',
	'Subtle Zebra 3D',
	'Subtlenet',
	'Tactile Noise',
	'Tasky',
	'Textured Stripes',
	'Texturetastic Gray',
	'Tileable Wood',
	'Tiny Grid',
	'Triangles Light',
	'Triangles',
	'Txture',
	'Use Your Illusion',
	'Vaio Hard Edge',
	'Vertical Cloth',
	'Vichy',
	'Vintage Speckles',
	'Weave',
	'White Brick Wall',
	'White Carbon',
	'White Carbonfiber',
	'White Plaster',
	'White Tiles',
	'White Wave',
	'Wide Rectangles',
	'Wood'
);